### PR TITLE
Fix panic for strings less than 3 chars

### PR DESCRIPTION
**Pull request by imikushin**
Fix panic for strings less than 3 chars.

Signed-off-by: Ivan Mikushin <i.mikushin@gmail.com>

### CODE REVIEW

**Comment by ematpl** [comment]
Hi, @imikushin,

Thanks for the PR! Before we can do any evaluation of it, though, we need you to submit an individual CLA, or to expose your membership in a GitHub organization associated to a corporate CLA. Dreddbot has helpfully provided some instructions for that above.

Thanks again,
Eric, CF Runtime Diego PM

**Comment by imikushin** [comment]
@ematpl Done.

**Comment by ematpl** [comment]
Thanks, @imikushin. I'm going to close and re-open the PR to allow Dreddbot to re-evaluate your CLA status.

**Comment by imikushin** [comment]
@ematpl Someone behind your CLA email has received and viewed the CLA (as reported by HelloSign).

**Comment by imikushin** [comment]
@ematpl Any progress on this PR / my CLA?

**Comment by ematpl** [comment]
Hi, @imikushin,

I don't think Dreddbot has been reconfigured with your GitHub handle or email yet, which is why the re-check didn't take yesterday. I've sent an email to the staff at the CF Foundation to verify your CLA outside of Dreddbot's check.

In the meantime, I'm curious: is there a particular reproduction case for the panic you've observed? If so, could you please supply it, and make sure to incorporate it as a test case here?

Thanks,
Eric

**Comment by imikushin** [comment]
@ematpl I'm surprised no-one got hurt by this yet: if you encode a string, such as "`.`" or "`-`", you'll get a panic. 

Added a test case. Feel free to run it without the previous commit :wink:

**Comment by imikushin** [comment]
@ematpl FYI, I've re-sent my CLA. I thought, maybe the problem was it had been sent from a different email address (by HelloSign, on my behalf).

Also, please, do look at the test case I'm providing: it's trivial and reliably triggers a panic (with an unpatched emitter.go).

**Comment by ematpl** [comment]
Thanks, @imikushin! I've been assured your CLA is good to go, and I've prioritized your PR for review by the Diego team. I've also verified your case independently: our [spiff](https://github.com/cloudfoundry-incubator/spiff) command-line tool uses candiedyaml internally, and `spiff merge <(echo 'foo: "-"')` does panic unexpectedly.

Thanks again,
Eric

**Comment by imikushin** [comment]
Hey @ematpl 
Any news on this PR? It's been a while now.

**Pull request merged**
